/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2017-9-26: 21h:41m
**
*/

/* ATSextcode_beg() */
//
var
theCanvas =
document.getElementById("theCanvas");
var
theCtx = theCanvas.getContext( '2d' );
//
var N = 6;
//
var W =
theCanvas.width;
var H =
theCanvas.height;
var WH = Math.min(W, H);
var WH2 = 0.88 * WH;
//
function
midpoint1
(p1, p2)
{
//
  var
  xmid = (2*p1.x + 1*p2.x)/3;
  var
  ymid = (2*p1.y + 1*p2.y)/3;
//
  return { x: xmid, y: ymid };
//
}
function
midpoint2
(p1, p2)
{
//
  var
  xmid = (1*p1.x + 2*p2.x)/3;
  var
  ymid = (1*p1.y + 2*p2.y)/3;
//
  return { x: xmid, y: ymid };
//
}
//
function
QuadrangleRemove
 (A, B, C, D)
{
  theCtx.save();
//
  theCtx.beginPath();
  theCtx.moveTo(A.x, A.y);
  theCtx.lineTo(B.x, B.y);
  theCtx.lineTo(C.x, C.y);
  theCtx.lineTo(D.x, D.y);
  theCtx.closePath();
//
  theCtx.fill();
//
  theCtx.restore();
} // end of [QuadrangleRemove]
//
/* ATSextcode_end() */

function
__patsfun_4__closurerize(env0, env1, env2, env3)
{
  return [function(cenv) { return __patsfun_4(cenv[1], cenv[2], cenv[3], cenv[4]); }, env0, env1, env2, env3];
}


function
SierpinskiDraw(arg0, arg1, arg2, arg3, arg4)
{
//
// knd = 1
  var apy0
  var apy1
  var apy2
  var apy3
  var apy4
  var tmp1
  var tmp2
  var tmp3
  var tmp4
  var tmp5
  var tmp6
  var tmp7
  var tmp8
  var tmp9
  var tmp10
  var tmp11
  var tmp12
  var tmp13
  var tmp16
  var tmp18
  var tmp20
  var tmp22
  var tmp24
  var tmp26
  var tmp28
  var tmp29
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_SierpinskiDraw
    tmp1 = ats2jspre_gt_int0_int0(arg0, 0);
    if(tmp1) {
      tmp2 = midpoint1(arg1, arg2);
      tmp3 = midpoint2(arg1, arg2);
      tmp4 = midpoint1(arg2, arg3);
      tmp5 = midpoint2(arg2, arg3);
      tmp6 = midpoint1(arg3, arg4);
      tmp7 = midpoint2(arg3, arg4);
      tmp8 = midpoint1(arg4, arg1);
      tmp9 = midpoint2(arg4, arg1);
      tmp10 = midpoint1(tmp9, tmp4);
      tmp11 = midpoint2(tmp9, tmp4);
      tmp12 = midpoint1(tmp5, tmp8);
      tmp13 = midpoint2(tmp5, tmp8);
      QuadrangleRemove(tmp10, tmp11, tmp12, tmp13);
      tmp16 = ats2jspre_sub_int0_int0(arg0, 1);
      SierpinskiDraw(tmp16, arg1, tmp2, tmp10, tmp9);
      tmp18 = ats2jspre_sub_int0_int0(arg0, 1);
      SierpinskiDraw(tmp18, tmp3, arg2, tmp4, tmp11);
      tmp20 = ats2jspre_sub_int0_int0(arg0, 1);
      SierpinskiDraw(tmp20, tmp12, tmp5, arg3, tmp6);
      tmp22 = ats2jspre_sub_int0_int0(arg0, 1);
      SierpinskiDraw(tmp22, tmp8, tmp13, tmp7, arg4);
      tmp24 = ats2jspre_sub_int0_int0(arg0, 1);
      SierpinskiDraw(tmp24, tmp2, tmp3, tmp11, tmp10);
      tmp26 = ats2jspre_sub_int0_int0(arg0, 1);
      SierpinskiDraw(tmp26, tmp11, tmp4, tmp5, tmp12);
      tmp28 = ats2jspre_sub_int0_int0(arg0, 1);
      SierpinskiDraw(tmp28, tmp13, tmp12, tmp6, tmp7);
      tmp29 = ats2jspre_sub_int0_int0(arg0, 1);
      // ATStailcalseq_beg
      apy0 = tmp29;
      apy1 = tmp9;
      apy2 = tmp10;
      apy3 = tmp13;
      apy4 = tmp8;
      arg0 = apy0;
      arg1 = apy1;
      arg2 = apy2;
      arg3 = apy3;
      arg4 = apy4;
      funlab_js = 1; // __patsflab_SierpinskiDraw
      // ATStailcalseq_end
    } else {
      // ATSINSmove_void
    } // end-of-if
    if (funlab_js > 0) continue; else return/*_void*/;
  } // endwhile-fun
} // end-of-function


function
_057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_057_assigns_057_assign02_057_Solution_057_Sierpinski_carpet_057_Sierpinski_carpet_056_dats__execute_after(arg0, arg1)
{
//
// knd = 0
  var tmp31
  var tmplab, tmplab_js
//
  // __patsflab_execute_after
  tmp31 = ats2jspre_cloref2fun0(arg0);
  setTimeout(tmp31, arg1);
  return/*_void*/;
} // end-of-function


function
repeat_execute_after(arg0, arg1, arg2)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_repeat_execute_after
  auxmain_3(arg0, arg1, arg2, 0);
  return/*_void*/;
} // end-of-function


function
auxmain_3(env0, env1, env2, arg0)
{
//
// knd = 1
  var apy0
  var tmp34
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_auxmain_3
    tmp34 = ats2jspre_gte_int0_int0(arg0, env0);
    if(tmp34) {
      // ATStailcalseq_beg
      apy0 = 0;
      arg0 = apy0;
      funlab_js = 1; // __patsflab_auxmain_3
      // ATStailcalseq_end
    } else {
      env1(arg0);
      _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_057_assigns_057_assign02_057_Solution_057_Sierpinski_carpet_057_Sierpinski_carpet_056_dats__execute_after(__patsfun_4__closurerize(env0, env1, env2, arg0), env2);
    } // end-of-if
    if (funlab_js > 0) continue; else return/*_void*/;
  } // endwhile-fun
} // end-of-function


function
__patsfun_4(env0, env1, env2, env3)
{
//
// knd = 0
  var tmp37
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_4
  tmp37 = ats2jspre_add_int0_int0(env3, 1);
  auxmain_3(env0, env1, env2, tmp37);
  return/*_void*/;
} // end-of-function


/* ATSextcode_beg() */
//
function
SierpinskiMain()
{
var A0 =
{x:   0, y: 0   };
var B0 =
{x: WH2, y: 0   };
var C0 =
{x: WH2, y: WH2 };
var D0 =
{x:   0, y: WH2 };
//
theCtx.translate
((W-WH2)/2, (H-WH2)/2);
//
repeat_execute_after
(
N
,
function(i)
{
theCtx.fillStyle="#0000ff";
QuadrangleRemove(A0, B0, C0, D0);
theCtx.fillStyle="#ffff00";
SierpinskiDraw(i, A0, B0, C0, D0);
}
,
1000/*delay in ms*/
);
}
//
/* ATSextcode_end() */

/* ATSextcode_beg() */
//
jQuery(document).ready(function(){SierpinskiMain();});
//
/* ATSextcode_end() */

/* ****** ****** */

/* end-of-compilation-unit */
