/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2017-9-27:  8h:47m
**
*/

/* ATSextcode_beg() */
//
function
document_getElementById
  (id)
{
  return document.getElementById(id);
}
//
function
xmldoc_set_innerHTML
  (xmldoc, text)
  { xmldoc.innerHTML = text; return; }
//
/* ATSextcode_end() */

/* ATSextcode_beg() */
function
funarg1_get()
{
  return parseInt(document.getElementById("funarg1").value);
}
/* ATSextcode_end() */

function
Factorial__patsfun_84__closurerize(env0)
{
  return [function(cenv) { return Factorial__patsfun_84(cenv[1]); }, env0];
}


function
Factorial__patsfun_34__34__1__closurerize()
{
  return [function(cenv, arg0, arg1) { return Factorial__patsfun_34__34__1(arg0, arg1); }];
}


function
Factorial__patsfun_111__closurerize(env0)
{
  return [function(cenv, arg0, arg1) { return Factorial__patsfun_111(cenv[1], arg0, arg1); }, env0];
}


function
_057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__int_stream_from(arg0)
{
//
// knd = 0
  var tmpret234
  var tmplab, tmplab_js
//
  // __patsflab_int_stream_from
  tmpret234 = ATSPMVlazyval(Factorial__patsfun_84__closurerize(arg0));
  return tmpret234;
} // end-of-function


function
Factorial__patsfun_84(env0)
{
//
// knd = 0
  var tmpret235
  var tmp236
  var tmp237
  var tmplab, tmplab_js
//
  // __patsflab_Factorial__patsfun_84
  tmp237 = ats2jspre_add_int0_int0(env0, 1);
  tmp236 = _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__int_stream_from(tmp237);
  tmpret235 = [env0, tmp236];
  return tmpret235;
} // end-of-function


function
_057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__succ_intrep(arg0)
{
//
// knd = 0
  var tmpret277
  var tmp278
  var tmp279
  var tmp280
  var tmp281
  var tmp282
  var tmp283
  var tmp284
  var tmplab, tmplab_js
//
  // __patsflab_succ_intrep
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab122
      if(ATSCKptriscons(arg0)) {
        { tmplab_js = 4; break; }
      } // ifthen
      case 2: // __atstmplab123
      tmp280 = null;
      tmpret277 = [1, tmp280];
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab124
      case 4: // __atstmplab125
      tmp278 = arg0[0];
      tmp279 = arg0[1];
      tmp281 = ats2jspre_add_int0_int0(tmp278, 1);
      tmp282 = ats2jspre_lt_int0_int0(tmp281, 10);
      if(tmp282) {
        tmpret277 = [tmp281, tmp279];
      } else {
        tmp283 = ats2jspre_sub_int0_int0(tmp281, 10);
        tmp284 = _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__succ_intrep(tmp279);
        tmpret277 = [tmp283, tmp284];
      } // end-of-if
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret277;
} // end-of-function


function
Factorial__add_int_intrep_97(arg0, arg1)
{
//
// knd = 0
  var tmpret285
  var tmp286
  var tmp287
  var tmp288
  var tmp289
  var tmp290
  var tmp291
  var tmp292
  var tmplab, tmplab_js
//
  // __patsflab_Factorial__add_int_intrep_97
  tmp286 = ats2jspre_gt_int0_int0(arg0, 0);
  if(tmp286) {
    // ATScaseofseq_beg
    tmplab_js = 1;
    while(true) {
      tmplab = tmplab_js; tmplab_js = 0;
      switch(tmplab) {
        // ATSbranchseq_beg
        case 1: // __atstmplab126
        if(ATSCKptriscons(arg1)) {
          { tmplab_js = 4; break; }
        } // ifthen
        case 2: // __atstmplab127
        tmpret285 = _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__intrep_make_int(arg0);
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        case 3: // __atstmplab128
        case 4: // __atstmplab129
        tmp287 = arg1[0];
        tmp288 = arg1[1];
        tmp289 = ats2jspre_add_int0_int0(arg0, tmp287);
        tmp290 = ats2jspre_mod_int0_int0(tmp289, 10);
        tmp291 = ats2jspre_div_int0_int0(tmp289, 10);
        tmp292 = Factorial__add_int_intrep_97(tmp291, tmp288);
        tmpret285 = [tmp290, tmp292];
        break;
        // ATSbranchseq_end
      } // end-of-switch
      if (tmplab_js === 0) break;
    } // endwhile
    // ATScaseofseq_end
  } else {
    tmpret285 = arg1;
  } // end-of-if
  return tmpret285;
} // end-of-function


function
_057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__add_intrep_intrep(arg0, arg1)
{
//
// knd = 0
  var tmpret293
  var tmp294
  var tmp295
  var tmp296
  var tmp297
  var tmp298
  var tmp299
  var tmp300
  var tmp301
  var tmp302
  var tmplab, tmplab_js
//
  // __patsflab_add_intrep_intrep
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab130
      if(ATSCKptriscons(arg0)) {
        { tmplab_js = 3; break; }
      } // ifthen
      case 2: // __atstmplab131
      tmpret293 = arg1;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab132
      if(ATSCKptriscons(arg1)) {
        { tmplab_js = 5; break; }
      } // ifthen
      case 4: // __atstmplab133
      tmpret293 = arg0;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 5: // __atstmplab134
      case 6: // __atstmplab135
      case 7: // __atstmplab136
      tmp294 = arg0[0];
      tmp295 = arg0[1];
      tmp296 = arg1[0];
      tmp297 = arg1[1];
      tmp298 = ats2jspre_add_int0_int0(tmp294, tmp296);
      tmp299 = _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__add_intrep_intrep(tmp295, tmp297);
      tmp300 = ats2jspre_lt_int0_int0(tmp298, 10);
      if(tmp300) {
        tmpret293 = [tmp298, tmp299];
      } else {
        tmp301 = ats2jspre_sub_int0_int0(tmp298, 10);
        tmp302 = _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__succ_intrep(tmp299);
        tmpret293 = [tmp301, tmp302];
      } // end-of-if
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret293;
} // end-of-function


function
_057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__mul_int_intrep(arg0, arg1)
{
//
// knd = 0
  var tmpret303
  var tmp304
  var tmp305
  var tmp306
  var tmp307
  var tmp308
  var tmp309
  var tmp310
  var tmp311
  var tmplab, tmplab_js
//
  // __patsflab_mul_int_intrep
  tmp304 = ats2jspre_gt_int0_int0(arg0, 0);
  if(tmp304) {
    // ATScaseofseq_beg
    tmplab_js = 1;
    while(true) {
      tmplab = tmplab_js; tmplab_js = 0;
      switch(tmplab) {
        // ATSbranchseq_beg
        case 1: // __atstmplab137
        if(ATSCKptriscons(arg1)) {
          { tmplab_js = 4; break; }
        } // ifthen
        case 2: // __atstmplab138
        tmpret303 = null;
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        case 3: // __atstmplab139
        case 4: // __atstmplab140
        tmp305 = arg1[0];
        tmp306 = arg1[1];
        tmp307 = ats2jspre_mul_int0_int0(arg0, tmp305);
        tmp308 = ats2jspre_mod_int0_int0(tmp307, 10);
        tmp309 = ats2jspre_div_int0_int0(tmp307, 10);
        tmp311 = _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__mul_int_intrep(arg0, tmp306);
        tmp310 = Factorial__add_int_intrep_97(tmp309, tmp311);
        tmpret303 = [tmp308, tmp310];
        break;
        // ATSbranchseq_end
      } // end-of-switch
      if (tmplab_js === 0) break;
    } // endwhile
    // ATScaseofseq_end
  } else {
    tmpret303 = null;
  } // end-of-if
  return tmpret303;
} // end-of-function


function
_057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__mul_intrep_intrep(arg0, arg1)
{
//
// knd = 0
  var tmpret312
  var tmplab, tmplab_js
//
  // __patsflab_mul_intrep_intrep
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab145
      if(ATSCKptriscons(arg1)) {
        { tmplab_js = 4; break; }
      } // ifthen
      case 2: // __atstmplab146
      tmpret312 = null;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab147
      case 4: // __atstmplab148
      tmpret312 = Factorial__auxmain_101(arg1, arg0);
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret312;
} // end-of-function


function
Factorial__auxmain_101(env0, arg0)
{
//
// knd = 0
  var tmpret313
  var tmp314
  var tmp315
  var tmp316
  var tmp317
  var tmp318
  var tmplab, tmplab_js
//
  // __patsflab_Factorial__auxmain_101
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab141
      if(ATSCKptriscons(arg0)) {
        { tmplab_js = 4; break; }
      } // ifthen
      case 2: // __atstmplab142
      tmpret313 = null;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab143
      case 4: // __atstmplab144
      tmp314 = arg0[0];
      tmp315 = arg0[1];
      tmp316 = _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__mul_int_intrep(tmp314, env0);
      tmp318 = _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__mul_intrep_intrep(tmp315, env0);
      tmp317 = [0, tmp318];
      tmpret313 = _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__add_intrep_intrep(tmp316, tmp317);
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret313;
} // end-of-function


function
_057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__intrep_make_int(arg0)
{
//
// knd = 0
  var tmpret319
  var tmp320
  var tmp321
  var tmp322
  var tmp323
  var tmplab, tmplab_js
//
  // __patsflab_intrep_make_int
  tmp320 = ats2jspre_gt_int0_int0(arg0, 0);
  if(tmp320) {
    tmp321 = ats2jspre_mod_int0_int0(arg0, 10);
    tmp322 = ats2jspre_div_int0_int0(arg0, 10);
    tmp323 = _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__intrep_make_int(tmp322);
    tmpret319 = [tmp321, tmp323];
  } else {
    tmpret319 = null;
  } // end-of-if
  return tmpret319;
} // end-of-function


function
_057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__print_intrep(arg0)
{
//
// knd = 0
  var tmpret324
  var tmp335
  var tmplab, tmplab_js
//
  // __patsflab_print_intrep
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab149
      if(ATSCKptriscons(arg0)) {
        { tmplab_js = 4; break; }
      } // ifthen
      case 2: // __atstmplab150
      ats2jspre_print_int(0);
      tmpret324 = 0;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab151
      case 4: // __atstmplab152
      tmp335 = _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__list0_reverse__32__1(arg0);
      tmpret324 = Factorial__auxmain_104(0, 0, tmp335);
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret324;
} // end-of-function


function
Factorial__auxmain_104(arg0, arg1, arg2)
{
//
// knd = 1
  var apy0
  var apy1
  var apy2
  var tmpret326
  var tmp327
  var tmp328
  var tmp330
  var tmp332
  var tmp333
  var tmp334
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_Factorial__auxmain_104
    // ATScaseofseq_beg
    tmplab_js = 1;
    while(true) {
      tmplab = tmplab_js; tmplab_js = 0;
      switch(tmplab) {
        // ATSbranchseq_beg
        case 1: // __atstmplab153
        if(ATSCKptriscons(arg2)) {
          { tmplab_js = 4; break; }
        } // ifthen
        case 2: // __atstmplab154
        tmpret326 = arg0;
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        case 3: // __atstmplab155
        case 4: // __atstmplab156
        tmp327 = arg2[0];
        tmp328 = arg2[1];
        tmp330 = ats2jspre_eq_int0_int0(arg1, 80);
        if(tmp330) {
          ats2jspre_print_newline();
        } else {
          // ATSINSmove_void
        } // end-of-if
        ats2jspre_print_int(tmp327);
        tmp332 = ats2jspre_add_int0_int0(arg0, 1);
        tmp334 = ats2jspre_eq_int0_int0(arg1, 80);
        if(tmp334) {
          tmp333 = 1;
        } else {
          tmp333 = ats2jspre_add_int0_int0(arg1, 1);
        } // end-of-if
        // ATStailcalseq_beg
        apy0 = tmp332;
        apy1 = tmp333;
        apy2 = tmp328;
        arg0 = apy0;
        arg1 = apy1;
        arg2 = apy2;
        funlab_js = 1; // __patsflab_Factorial__auxmain_104
        // ATStailcalseq_end
        break;
        // ATSbranchseq_end
      } // end-of-switch
      if (tmplab_js === 0) break;
    } // endwhile
    // ATScaseofseq_end
    if (funlab_js > 0) continue; else return tmpret326;
  } // endwhile-fun
} // end-of-function


function
_057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__list0_reverse__32__1(arg0)
{
//
// knd = 0
  var tmpret65__1
  var tmp66__1
  var tmplab, tmplab_js
//
  // __patsflab_list0_reverse
  tmp66__1 = null;
  tmpret65__1 = _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__list0_revappend__33__1(arg0, tmp66__1);
  return tmpret65__1;
} // end-of-function


function
_057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__list0_revappend__33__1(arg0, arg1)
{
//
// knd = 0
  var tmpret67__1
  var tmplab, tmplab_js
//
  // __patsflab_list0_revappend
  tmpret67__1 = _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__list0_foldleft__22__1(arg0, arg1, Factorial__patsfun_34__34__1__closurerize());
  return tmpret67__1;
} // end-of-function


function
_057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__list0_foldleft__22__1(arg0, arg1, arg2)
{
//
// knd = 0
  var tmpret48__1
  var tmplab, tmplab_js
//
  // __patsflab_list0_foldleft
  tmpret48__1 = Factorial__loop_23__23__1(arg2, arg0, arg1);
  return tmpret48__1;
} // end-of-function


function
Factorial__loop_23__23__1(env0, arg0, arg1)
{
//
// knd = 1
  var apy0
  var apy1
  var tmpret49__1
  var tmp50__1
  var tmp51__1
  var tmp52__1
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_Factorial__loop_23
    // ATScaseofseq_beg
    tmplab_js = 1;
    while(true) {
      tmplab = tmplab_js; tmplab_js = 0;
      switch(tmplab) {
        // ATSbranchseq_beg
        case 1: // __atstmplab8
        if(ATSCKptriscons(arg0)) {
          { tmplab_js = 4; break; }
        } // ifthen
        case 2: // __atstmplab9
        tmpret49__1 = arg1;
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        case 3: // __atstmplab10
        case 4: // __atstmplab11
        tmp50__1 = arg0[0];
        tmp51__1 = arg0[1];
        tmp52__1 = env0[0](env0, arg1, tmp50__1);
        // ATStailcalseq_beg
        apy0 = tmp51__1;
        apy1 = tmp52__1;
        arg0 = apy0;
        arg1 = apy1;
        funlab_js = 1; // __patsflab_Factorial__loop_23
        // ATStailcalseq_end
        break;
        // ATSbranchseq_end
      } // end-of-switch
      if (tmplab_js === 0) break;
    } // endwhile
    // ATScaseofseq_end
    if (funlab_js > 0) continue; else return tmpret49__1;
  } // endwhile-fun
} // end-of-function


function
Factorial__patsfun_34__34__1(arg0, arg1)
{
//
// knd = 0
  var tmpret68__1
  var tmplab, tmplab_js
//
  // __patsflab_Factorial__patsfun_34
  tmpret68__1 = [arg1, arg0];
  return tmpret68__1;
} // end-of-function


function
Factorial__Factorial_110(arg0)
{
//
// knd = 0
  var tmpret345
  var tmp351
  var tmp352
  var tmplab, tmplab_js
//
  // __patsflab_Factorial__Factorial_110
  tmp352 = null;
  tmp351 = [1, tmp352];
  tmpret345 = Factorial__patsfun_111__closurerize(arg0)[0](Factorial__patsfun_111__closurerize(arg0), 0, tmp351);
  return tmpret345;
} // end-of-function


function
Factorial__patsfun_111(env0, arg0, arg1)
{
//
// knd = 1
  var apy0
  var apy1
  var tmpret346
  var tmp347
  var tmp348
  var tmp349
  var tmp350
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_Factorial__patsfun_111
    tmp347 = ats2jspre_lt_int0_int0(arg0, env0);
    if(tmp347) {
      tmp348 = ats2jspre_add_int0_int0(arg0, 1);
      tmp350 = ats2jspre_add_int0_int0(arg0, 1);
      tmp349 = _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__mul_int_intrep(tmp350, arg1);
      // ATStailcalseq_beg
      apy0 = tmp348;
      apy1 = tmp349;
      arg0 = apy0;
      arg1 = apy1;
      funlab_js = 1; // __patsflab_Factorial__patsfun_111
      // ATStailcalseq_end
    } else {
      tmpret346 = arg1;
    } // end-of-if
    if (funlab_js > 0) continue; else return tmpret346;
  } // endwhile-fun
} // end-of-function


function
Factorial__evaluate()
{
//
// knd = 0
  var tmp355
  var tmp360
  var tmp361
  var tmp362
  var tmp363
  var tmplab, tmplab_js
//
  // __patsflab_Factorial__evaluate
  ats2jspre_the_print_store_clear();
  tmp355 = funarg1_get();
  ats2jspre_print_string("The factorial of ");
  ats2jspre_print_int(tmp355);
  ats2jspre_print_string(" is:");
  ats2jspre_print_newline();
  tmp361 = Factorial__Factorial_110(tmp355);
  tmp360 = _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__print_intrep(tmp361);
  tmp362 = document_getElementById("theOutput");
  tmp363 = ats2jspre_the_print_store_join();
  xmldoc_set_innerHTML(tmp362, tmp363);
  return/*_void*/;
} // end-of-function

// dynloadflag_minit
var _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__dynloadflag = 0;

function
_057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__dynload()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // ATSdynload()
  // ATSdynloadflag_sta(_057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__dynloadflag(274))
  if(ATSCKiseqz(_057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__dynloadflag)) {
    _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__dynloadflag = 1 ; // flag is set
  } // end-of-if
  return/*_void*/;
} // end-of-function


function
Factorial__dynload()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  _057_home_057_hwxi_057_Teaching_057_CS320_057_cs320_055_2017_055_fall_055_hwxi_057_assigns_057_assign03_057_MySolution_057_Factorial_056_dats__dynload();
  return/*_void*/;
} // end-of-function


/* ATSextcode_beg() */
//
function
Factorial__initize()
{
//
Factorial__dynload(); return;
//
} // end of [Factorial_initize]
/* ATSextcode_end() */

/* ATSextcode_beg() */
//
jQuery(document).ready(function(){Factorial__initize();});
//
/* ATSextcode_end() */

/* ****** ****** */

/* end-of-compilation-unit */
